In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import  seaborn as sns 


In [2]:
df = pd.read_csv("E:\DATA ANLYST\material\spam.csv")

In [3]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [9]:
df['spam'] = df['Category'].apply( lambda X :  1 if X== 'spam'  else 0  ) 
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection  import train_test_split
X_train , X_test , y_train, y_test = train_test_split( df['Message']  , df['spam'] , test_size= 0.25 )   


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer 

v = CountVectorizer() 

X_train_count = v.fit_transform( X_train.values)

In [47]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4179, 7524))

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [49]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)


array([0, 1])

In [50]:
X_test_count = v.transform(X_test) 
model.score( X_test_count ,  y_test)

0.9870782483847811

Sklearn Pipeline




In [51]:
from sklearn.pipeline import Pipeline 
clf = Pipeline( 
    [ 
        ( 'vectorizer'   , CountVectorizer() ) ,
        ( 'nb'  , MultinomialNB() ) 
    ]
)

clf.fit( X_train  ,y_train  )





Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [52]:
clf.score( X_test , y_test )

0.9870782483847811

In [53]:
clf.predict( emails )

array([0, 1])

NEW  EXCERSISE 


In [ ]:
from sklearn import datasets
wine = datasets.load_wine()

In [ ]:
wine.feature_names 

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [58]:
ww = pd.DataFrame( wine.data , columns=wine.feature_names )

In [59]:
ww

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [60]:
ww['target'] = wine.target

In [64]:
from sklearn.model_selection import train_test_split 

wx_train , wx_test , wy_train , wy_test  = train_test_split( wine.data  , wine.target  , test_size=  0.3  , random_state= 27)

array([[1.208e+01, 1.330e+00, 2.300e+00, ..., 1.070e+00, 3.210e+00,
        6.250e+02],
       [1.305e+01, 5.800e+00, 2.130e+00, ..., 7.300e-01, 3.100e+00,
        3.800e+02],
       [1.220e+01, 3.030e+00, 2.320e+00, ..., 6.600e-01, 1.830e+00,
        5.100e+02],
       ...,
       [1.358e+01, 1.660e+00, 2.360e+00, ..., 1.090e+00, 2.880e+00,
        1.515e+03],
       [1.349e+01, 1.660e+00, 2.240e+00, ..., 9.800e-01, 2.780e+00,
        4.720e+02],
       [1.364e+01, 3.100e+00, 2.560e+00, ..., 9.600e-01, 3.360e+00,
        8.450e+02]], shape=(124, 13))

In [66]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB 
from sklearn.pipeline import Pipeline 

kaka = Pipeline( 
    [
        ( 'gaussian data '  , GaussianNB())
    ]
)

kaka.fit( wx_train , wy_train)

Pipeline(steps=[('gaussian data ', GaussianNB())])

In [69]:
bagge = Pipeline(
    [
        ( ' multinomail '  , MultinomialNB())
    ]
 )

bagge.fit(wx_train , wy_train)

Pipeline(steps=[(' multinomail ', MultinomialNB())])

In [71]:
bagge.score( wx_test , wy_test) 


0.7962962962962963

In [73]:
kaka.score( wx_test , wy_test )

1.0

In [78]:
cliff = kaka.predict( wx_test)

In [79]:
from sklearn.metrics import accuracy_score
accuracy_score( wy_test , cliff  )  

1.0