In [53]:
#E:\DATA ANLYST\material\homeprices.csv

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns


In [54]:
df = pd.read_csv( 'E:\DATA ANLYST\material\homeprices.csv')

In [55]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [56]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder() 



In [57]:
dfle = df 
dfle.town = le.fit_transform( dfle.town )

In [58]:
dfle 

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [59]:
X = dfle[ [ 'town' , 'area' ] ]
y = dfle.price 
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [60]:
X

town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [61]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 
ct = ColumnTransformer( [('town'  , OneHotEncoder()  , [0] )]  , remainder= 'passthrough')  
X = ct.fit_transform( X )


In [62]:
X = X[ : , 1: ]

In [63]:
X 

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [64]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression( )

In [65]:
model.fit( X , y )

LinearRegression()

In [66]:
model.predict( [[0,1,3400]] )

array([681241.6684584])

In [67]:
kaka = pd.read_csv("E:\DATA ANLYST\material\carprices.csv")

In [68]:
kaka

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [69]:
kaka['Car Model']   =  le.fit_transform( kaka['Car Model'])

kaka

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [91]:
cct = ColumnTransformer( [ ( 'Car Model'  , OneHotEncoder()  ,  [0])]  , remainder='passthrough') 

In [82]:
cct

ColumnTransformer(remainder='passthrough',
                  transformers=[('Car Model', OneHotEncoder(), [0])])

In [92]:
kakaji = kaka 
y = kakaji['Sell Price($)']
X= kakaji[['Car Model' ,'Mileage' ,'Age(yrs)'] ] 
X

Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [93]:
X = cct.fit_transform(X) 
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [94]:
print(cct.named_transformers_)


{'Car Model': OneHotEncoder(), 'remainder': FunctionTransformer(accept_sparse=True, check_inverse=False,
                    feature_names_out='one-to-one')}


In [95]:
#X_transformed = cct.fit_transform(df)

ohe = cct.named_transformers_['Car Model']
car_feature_names = ohe.get_feature_names_out(input_features=['Car Model'])

# Combine with Remaining Column Names
new_feature_names = list(car_feature_names) + ['Mileage' ,'Age(yrs)']

In [96]:
new_feature_names

['Car Model_0', 'Car Model_1', 'Car Model_2', 'Mileage', 'Age(yrs)']

In [102]:
X = pd.DataFrame(  X , columns= new_feature_names)


In [106]:
model

LinearRegression()

In [107]:
model.fit( X , y  )

LinearRegression()

In [110]:
model.score( X  , y )

0.9417050937281083

In [ ]:
# BETTER APPROACH USE  PANDAS INSTEAD OF SK LEARN 

In [112]:
kaka

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [113]:
sharon  = pd.read_csv("E:\DATA ANLYST\material\carprices.csv")

In [114]:
sharon 

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [115]:
dummies = pd.get_dummies( sharon['Car Model'])

In [117]:
merged = pd.concat( [ sharon , dummies ]  ,  axis= 1 )
merged 

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6    False    True   
1                  BMW X5    35000          34000         3    False    True   
2                  BMW X5    57000          26100         5    False    True   
3                  BMW X5    22500          40000         2    False    True   
4                  BMW X5    46000          31500         4    False    True   
5                 Audi A5    59000          29400         5     True   False   
6                 Audi A5    52000          32000         5     True   False   
7                 Audi A5    72000          19300         6     True   False   
8                 Audi A5    91000          12000         8     True   False   
9   Mercedez Benz C class    67000          22000         6    False   False   
10  Mercedez Benz C class    83000          20000         7    False   False   
11  Mercedez Benz C class    79000          21000         7    False   False   
12  Mercedez Benz C class    59000          33000         5    False   False   

    Mercedez Benz C class  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
5                   False  
6                   False  
7                   False  
8                   False  
9                    True  
10                   True  
11                   True  
12                   True

In [119]:
sharon_f = merged.drop( ['Car Model'] , axis =1 )

In [120]:
sharon_f 


Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000          18000         6    False    True                  False
1     35000          34000         3    False    True                  False
2     57000          26100         5    False    True                  False
3     22500          40000         2    False    True                  False
4     46000          31500         4    False    True                  False
5     59000          29400         5     True   False                  False
6     52000          32000         5     True   False                  False
7     72000          19300         6     True   False                  False
8     91000          12000         8     True   False                  False
9     67000          22000         6    False   False                   True
10    83000          20000         7    False   False                   True
11    79000          21000         7    False   False                   True
12    59000          33000         5    False   False                   True

In [129]:
X_new = sharon_f.drop( ['Sell Price($)' ,'Mercedez Benz C class' ]  , axis =1 )

In [130]:
X_new 

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6    False    True
1     35000         3    False    True
2     57000         5    False    True
3     22500         2    False    True
4     46000         4    False    True
5     59000         5     True   False
6     52000         5     True   False
7     72000         6     True   False
8     91000         8     True   False
9     67000         6    False   False
10    83000         7    False   False
11    79000         7    False   False
12    59000         5    False   False

In [131]:
y_new = sharon_f['Sell Price($)']

In [125]:
y_new 

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [126]:
model

LinearRegression()

In [132]:
model.fit( X_new , y_new) 

LinearRegression()

In [133]:
model.score(X_new , y_new)

0.9417050937281083

In [134]:
model.predict([[45000,4,0,0]])


c:\Users\Ayush\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721061])